### ISSUE TITLE
docker-ssrmu: Can not use http_simple/http_post under python3

### ISSUE THREAD

**Issue by theBucky** [fanvinga/dockerfiles#3]
Please switch the python version into 2.X instead of 3.X in the docker-ssrmu container.

Best Regards,
Aaron Jaws.

**Comment by fanvinga** [comment]
After many people participated in the exhaustive test, the problem seems to fail to be accurately reproduced every time. Only in the case of http_post will there be a high probability that the connection cannot be reconnected.

However, given Python 2's library support and Python 3 performance optimization and enhancement, as well as the complexity of the current architecture. I don't think it should be replaced with the base image of Python2

I suggest that you avoid using the http_post option to minimize the probability of problems as a workaround.

I will continue to follow this issue, so please contact me as soon as possible if there are any updates.
